import type { Championship, ChampionshipCategory, Circuit } from "./types";

const championship = (
  id: string,
  name: string,
  shortName: string,
  category: ChampionshipCategory,
  color: string,
  officialUrl: string,
  providerId: string,
): Championship => ({
  id,
  name,
  shortName,
  category,
  color,
  officialUrl,
  providerId,
});

export const championships: Championship[] = [
  championship("f1", "Formula 1", "F1", "FORMULA", "#ff3548", "https://www.formula1.com/en/racing/2026", "f1-official"),
  championship("f2", "Formula 2", "F2", "FORMULA", "#38d98b", "https://www.fia.com/news/2026-fia-sporting-calendars-approved-world-motor-sport-council", "fia-calendars"),
  championship("f3", "Formula 3", "F3", "FORMULA", "#24b8ff", "https://www.fia.com/news/2026-fia-sporting-calendars-approved-world-motor-sport-council", "fia-calendars"),
  championship("fe", "Formula E", "FE", "FORMULA", "#735cff", "https://www.fiaformulae.com/en/calendar", "fia-calendars"),
  championship("indy", "IndyCar", "INDY", "FORMULA", "#4ba8ff", "https://www.indycar.com/schedule", "indycar-official"),
  championship("sf", "Super Formula", "SF", "FORMULA", "#d7dce3", "https://superformula.net/sf3/race_taxonomy/2026/", "super-formula-official"),
  championship("wec", "FIA World Endurance Championship", "WEC", "ENDURANCE", "#279cff", "https://www.fiawec.com/", "fia-calendars"),
  championship("imsa", "IMSA SportsCar Championship", "IMSA", "ENDURANCE", "#3e70ff", "https://www.imsa.com/weathertech/weathertech-2026-schedule/", "imsa-official"),
  championship("elms", "European Le Mans Series", "ELMS", "ENDURANCE", "#1f72d8", "https://www.europeanlemansseries.com/en/", "aco-calendars"),
  championship("alms", "Asian Le Mans Series", "ALMS", "ENDURANCE", "#e5b43b", "https://www.asianlemansseries.com/", "aco-calendars"),
  championship("mlmc", "Michelin Le Mans Cup", "MLMC", "ENDURANCE", "#37bd7b", "https://www.lemanscup.com/", "aco-calendars"),
  championship("nls", "Nürburgring Langstrecken-Serie", "NLS", "ENDURANCE", "#4ed180", "https://www.nuerburgring-langstrecken-serie.de/", "nls-official"),
  championship("n24", "Nürburgring 24 Hours", "N24", "ENDURANCE", "#f4f7fa", "https://www.24h-rennen.de/en/", "n24-official"),
  championship("gtwce", "GT World Challenge Europe", "GTWC", "GT", "#ff9f32", "https://www.gt-world-challenge-europe.com/calendar", "sro-official"),
  championship("gtwca", "GT World Challenge America", "GTAM", "GT", "#ffb13b", "https://www.gt-world-challenge-america.com/calendar", "sro-official"),
  championship("gtwcas", "GT World Challenge Asia", "GTAS", "GT", "#ff8735", "https://www.gt-world-challenge-asia.com/calendar", "sro-official"),
  championship("gtwcau", "GT World Challenge Australia", "GTAU", "GT", "#ee7336", "https://www.gt-world-challenge-australia.com/calendar", "sro-official"),
  championship("igtc", "Intercontinental GT Challenge", "IGTC", "GT", "#e67828", "https://www.intercontinentalgtchallenge.com/about/intercontinental-gt-challenge", "sro-official"),
  championship("britgt", "British GT", "BGT", "GT", "#56a1ff", "https://www.britishgt.com/calendar", "sro-official"),
  championship("gtopen", "International GT Open", "GTO", "GT", "#8f68ff", "https://gtopen.gtsport.es/calendario", "gt-open-official"),
  championship("dtm", "DTM", "DTM", "TOURING CARS", "#bec7d2", "https://www.dtm.com/data/events", "dtm-official"),
  championship("motogp", "MotoGP", "MGP", "MOTORCYCLES", "#f04444", "https://www.motogp.com/en/news/2025/07/24/le-calendrier-2026-du-motogp-devoile-/755478", "motogp-official"),
  championship("moto2", "Moto2", "M2", "MOTORCYCLES", "#e44f36", "https://www.motogp.com/en/calendar/2026", "motogp-official"),
  championship("moto3", "Moto3", "M3", "MOTORCYCLES", "#d4a63a", "https://www.motogp.com/en/calendar/2026", "motogp-official"),
  championship("wsbk", "World Superbike", "WSBK", "MOTORCYCLES", "#ff3448", "https://www.worldsbk.com/en/calendar", "worldsbk-official"),
  championship("wrc", "World Rally Championship", "WRC", "RALLY", "#55c5ff", "https://www.fia.com/news/2026-fia-sporting-calendars-approved-world-motor-sport-council", "fia-calendars"),
  championship("wrx", "FIA Rallycross", "RX", "RALLY", "#d8ff4f", "https://www.fia.com/news/fia-unveils-2026-european-rallycross-championship-calendar", "fia-calendars"),
  championship("nascar", "NASCAR Cup Series", "CUP", "AMERICAN MOTORSPORT", "#f4d03f", "https://www.nascar.com/news-media/2025/11/12/nascar-announces-start-times-networks-for-2026-national-series-races/", "nascar-official"),
  championship("xfinity", "NASCAR O'Reilly Auto Parts Series", "OAP", "AMERICAN MOTORSPORT", "#7d56ff", "https://www.nascar.com/news-media/2025/11/12/nascar-announces-start-times-networks-for-2026-national-series-races/", "nascar-official"),
  championship("trucks", "NASCAR Craftsman Truck Series", "NCTS", "AMERICAN MOTORSPORT", "#e64848", "https://www.nascar.com/news-media/2025/11/12/nascar-announces-start-times-networks-for-2026-national-series-races/", "nascar-official"),
  championship("dakar", "Dakar Rally", "DAKAR", "OTHER", "#e6aa52", "https://www.dakar.com/", "fia-calendars"),
];

const circuit = (
  id: string,
  name: string,
  country: string,
  countryCode: string,
  timezone: string,
  city?: string,
  lengthKm?: number,
  corners?: number,
): Circuit => ({ id, name, city, country, countryCode, timezone, lengthKm, corners });

export const circuits: Circuit[] = [
  circuit("melbourne", "Albert Park Circuit", "Australia", "AU", "Australia/Melbourne", "Melbourne", 5.278, 14),
  circuit("shanghai", "Shanghai International Circuit", "China", "CN", "Asia/Shanghai", "Shanghai", 5.451, 16),
  circuit("suzuka", "Suzuka Circuit", "Japan", "JP", "Asia/Tokyo", "Suzuka", 5.807, 18),
  circuit("miami", "Miami", "United States", "US", "America/New_York", "Miami"),
  circuit("montreal", "Circuit Gilles-Villeneuve", "Canada", "CA", "America/Toronto", "Montreal", 4.361, 14),
  circuit("monaco", "Circuit de Monaco", "Monaco", "MC", "Europe/Monaco", "Monte Carlo", 3.337, 19),
  circuit("barcelona", "Circuit de Barcelona-Catalunya", "Spain", "ES", "Europe/Madrid", "Barcelona", 4.657, 14),
  circuit("red-bull-ring", "Red Bull Ring", "Austria", "AT", "Europe/Vienna", "Spielberg", 4.318, 10),
  circuit("silverstone", "Silverstone Circuit", "United Kingdom", "GB", "Europe/London", "Silverstone", 5.891, 18),
  circuit("spa", "Circuit de Spa-Francorchamps", "Belgium", "BE", "Europe/Brussels", "Stavelot", 7.004, 19),
  circuit("hungaroring", "Hungaroring", "Hungary", "HU", "Europe/Budapest", "Mogyorod", 4.381, 14),
  circuit("zandvoort", "Circuit Zandvoort", "Netherlands", "NL", "Europe/Amsterdam", "Zandvoort", 4.259, 14),
  circuit("monza", "Autodromo Nazionale Monza", "Italy", "IT", "Europe/Rome", "Monza", 5.793, 11),
  circuit("madrid", "Madrid", "Spain", "ES", "Europe/Madrid", "Madrid"),
  circuit("baku", "Baku City Circuit", "Azerbaijan", "AZ", "Asia/Baku", "Baku", 6.003, 20),
  circuit("sepang", "Sepang International Circuit", "Malaysia", "MY", "Asia/Kuala_Lumpur", "Sepang", 5.543, 15),
  circuit("singapore", "Marina Bay Street Circuit", "Singapore", "SG", "Asia/Singapore", "Singapore", 4.94, 19),
  circuit("cota", "Circuit of the Americas", "United States", "US", "America/Chicago", "Austin", 5.513, 20),
  circuit("mexico-city", "Autodromo Hermanos Rodriguez", "Mexico", "MX", "America/Mexico_City", "Mexico City", 4.304, 17),
  circuit("interlagos", "Autodromo Jose Carlos Pace", "Brazil", "BR", "America/Sao_Paulo", "Sao Paulo", 4.309, 15),
  circuit("las-vegas", "Las Vegas Strip Circuit", "United States", "US", "America/Los_Angeles", "Las Vegas", 6.201, 17),
  circuit("lusail", "Lusail International Circuit", "Qatar", "QA", "Asia/Qatar", "Lusail", 5.419, 16),
  circuit("yas-marina", "Yas Marina Circuit", "United Arab Emirates", "AE", "Asia/Dubai", "Abu Dhabi", 5.281, 16),
  circuit("sao-paulo-street", "Sao Paulo Street Circuit", "Brazil", "BR", "America/Sao_Paulo", "Sao Paulo"),
  circuit("jeddah", "Jeddah Corniche Circuit", "Saudi Arabia", "SA", "Asia/Riyadh", "Jeddah", 6.174, 27),
  circuit("berlin-tempelhof", "Tempelhof Airport Street Circuit", "Germany", "DE", "Europe/Berlin", "Berlin"),
  circuit("sanya", "Sanya Street Circuit", "China", "CN", "Asia/Shanghai", "Sanya"),
  circuit("tokyo", "Tokyo Street Circuit", "Japan", "JP", "Asia/Tokyo", "Tokyo"),
  circuit("london-excel", "ExCeL London Circuit", "United Kingdom", "GB", "Europe/London", "London"),
  circuit("st-petersburg", "Streets of St. Petersburg", "United States", "US", "America/New_York", "St. Petersburg"),
  circuit("phoenix", "Phoenix Raceway", "United States", "US", "America/Phoenix", "Avondale"),
  circuit("arlington", "Streets of Arlington", "United States", "US", "America/Chicago", "Arlington"),
  circuit("barber", "Barber Motorsports Park", "United States", "US", "America/Chicago", "Birmingham"),
  circuit("long-beach", "Streets of Long Beach", "United States", "US", "America/Los_Angeles", "Long Beach"),
  circuit("indianapolis", "Indianapolis Motor Speedway", "United States", "US", "America/Indiana/Indianapolis", "Indianapolis", 4.023, 14),
  circuit("detroit", "Detroit Street Circuit", "United States", "US", "America/Detroit", "Detroit"),
  circuit("wwtr", "World Wide Technology Raceway", "United States", "US", "America/Chicago", "Madison"),
  circuit("road-america", "Road America", "United States", "US", "America/Chicago", "Elkhart Lake", 6.515, 14),
  circuit("mid-ohio", "Mid-Ohio Sports Car Course", "United States", "US", "America/New_York", "Lexington", 3.634, 13),
  circuit("nashville", "Nashville Superspeedway", "United States", "US", "America/Chicago", "Lebanon"),
  circuit("portland", "Portland International Raceway", "United States", "US", "America/Los_Angeles", "Portland"),
  circuit("markham", "Streets of Markham", "Canada", "CA", "America/Toronto", "Markham"),
  circuit("milwaukee", "Milwaukee Mile", "United States", "US", "America/Chicago", "West Allis"),
  circuit("laguna-seca", "WeatherTech Raceway Laguna Seca", "United States", "US", "America/Los_Angeles", "Monterey", 3.602, 11),
  circuit("motegi", "Mobility Resort Motegi", "Japan", "JP", "Asia/Tokyo", "Motegi"),
  circuit("autopolis", "Autopolis", "Japan", "JP", "Asia/Tokyo", "Hita"),
  circuit("fuji", "Fuji Speedway", "Japan", "JP", "Asia/Tokyo", "Oyama", 4.563, 16),
  circuit("sugo", "Sportsland SUGO", "Japan", "JP", "Asia/Tokyo", "Murata"),
  circuit("imola", "Autodromo Internazionale Enzo e Dino Ferrari", "Italy", "IT", "Europe/Rome", "Imola", 4.909, 19),
  circuit("le-mans", "Circuit de la Sarthe", "France", "FR", "Europe/Paris", "Le Mans", 13.626, 38),
  circuit("bahrain", "Bahrain International Circuit", "Bahrain", "BH", "Asia/Bahrain", "Sakhir", 5.412, 15),
  circuit("daytona", "Daytona International Speedway", "United States", "US", "America/New_York", "Daytona Beach", 5.729, 12),
  circuit("sebring", "Sebring International Raceway", "United States", "US", "America/New_York", "Sebring", 6.019, 17),
  circuit("watkins-glen", "Watkins Glen International", "United States", "US", "America/New_York", "Watkins Glen"),
  circuit("ctmp", "Canadian Tire Motorsport Park", "Canada", "CA", "America/Toronto", "Bowmanville"),
  circuit("vir", "Virginia International Raceway", "United States", "US", "America/New_York", "Alton", 5.263, 17),
  circuit("road-atlanta", "Michelin Raceway Road Atlanta", "United States", "US", "America/New_York", "Braselton", 4.088, 12),
  circuit("paul-ricard", "Circuit Paul Ricard", "France", "FR", "Europe/Paris", "Le Castellet"),
  circuit("portimao", "Autodromo Internacional do Algarve", "Portugal", "PT", "Europe/Lisbon", "Portimao"),
  circuit("dubai-autodrome", "Dubai Autodrome", "United Arab Emirates", "AE", "Asia/Dubai", "Dubai"),
  circuit("nurburgring", "Nürburgring Nordschleife", "Germany", "DE", "Europe/Berlin", "Nurburg", 20.832, 73),
  circuit("brands-hatch", "Brands Hatch", "United Kingdom", "GB", "Europe/London", "West Kingsdown"),
  circuit("misano", "Misano World Circuit Marco Simoncelli", "Italy", "IT", "Europe/Rome", "Misano Adriatico"),
  circuit("magny-cours", "Circuit de Nevers Magny-Cours", "France", "FR", "Europe/Paris", "Magny-Cours"),
  circuit("sonoma", "Sonoma Raceway", "United States", "US", "America/Los_Angeles", "Sonoma"),
  circuit("mandalika", "Pertamina Mandalika International Circuit", "Indonesia", "ID", "Asia/Makassar", "Lombok"),
  circuit("okayama", "Okayama International Circuit", "Japan", "JP", "Asia/Tokyo", "Mimasaka"),
  circuit("beijing", "Beijing Street Circuit", "China", "CN", "Asia/Shanghai", "Beijing"),
  circuit("phillip-island", "Phillip Island Grand Prix Circuit", "Australia", "AU", "Australia/Melbourne", "Phillip Island"),
  circuit("the-bend", "Shell V-Power Motorsport Park", "Australia", "AU", "Australia/Adelaide", "Tailem Bend"),
  circuit("queensland", "Queensland Raceway", "Australia", "AU", "Australia/Brisbane", "Ipswich"),
  circuit("hidden-valley", "Hidden Valley Raceway", "Australia", "AU", "Australia/Darwin", "Darwin"),
  circuit("sydney", "Sydney Motorsport Park", "Australia", "AU", "Australia/Sydney", "Eastern Creek"),
  circuit("adelaide", "Adelaide Street Circuit", "Australia", "AU", "Australia/Adelaide", "Adelaide"),
  circuit("mount-panorama", "Mount Panorama Circuit", "Australia", "AU", "Australia/Sydney", "Bathurst"),
  circuit("lausitzring", "DEKRA Lausitzring", "Germany", "DE", "Europe/Berlin", "Klettwitz"),
  circuit("norisring", "Norisring", "Germany", "DE", "Europe/Berlin", "Nuremberg"),
  circuit("oschersleben", "Motorsport Arena Oschersleben", "Germany", "DE", "Europe/Berlin", "Oschersleben"),
  circuit("sachsenring", "Sachsenring", "Germany", "DE", "Europe/Berlin", "Hohenstein-Ernstthal"),
  circuit("hockenheim", "Hockenheimring", "Germany", "DE", "Europe/Berlin", "Hockenheim"),
  circuit("oulton-park", "Oulton Park", "United Kingdom", "GB", "Europe/London", "Little Budworth"),
  circuit("snetterton", "Snetterton 300", "United Kingdom", "GB", "Europe/London", "Norwich"),
  circuit("donington", "Donington Park", "United Kingdom", "GB", "Europe/London", "Castle Donington"),
  circuit("buriram", "Chang International Circuit", "Thailand", "TH", "Asia/Bangkok", "Buriram"),
  circuit("goiania", "Autodromo Internacional Ayrton Senna", "Brazil", "BR", "America/Sao_Paulo", "Goiania"),
  circuit("jerez", "Circuito de Jerez - Angel Nieto", "Spain", "ES", "Europe/Madrid", "Jerez"),
  circuit("le-mans-bugatti", "Bugatti Circuit", "France", "FR", "Europe/Paris", "Le Mans"),
  circuit("mugello", "Autodromo Internazionale del Mugello", "Italy", "IT", "Europe/Rome", "Scarperia"),
  circuit("balaton", "Balaton Park Circuit", "Hungary", "HU", "Europe/Budapest", "Balatonfokajar"),
  circuit("brno", "Automotodrom Brno", "Czechia", "CZ", "Europe/Prague", "Brno"),
  circuit("assen", "TT Circuit Assen", "Netherlands", "NL", "Europe/Amsterdam", "Assen"),
  circuit("motorland", "MotorLand Aragon", "Spain", "ES", "Europe/Madrid", "Alcaniz"),
  circuit("valencia", "Circuit Ricardo Tormo", "Spain", "ES", "Europe/Madrid", "Cheste"),
  circuit("most", "Autodrom Most", "Czechia", "CZ", "Europe/Prague", "Most"),
  circuit("cremona", "Cremona Circuit", "Italy", "IT", "Europe/Rome", "Cremona"),
  circuit("estoril", "Circuito do Estoril", "Portugal", "PT", "Europe/Lisbon", "Estoril"),
  circuit("monte-carlo-rally", "Rallye Monte-Carlo", "Monaco", "MC", "Europe/Monaco", "Monaco"),
  circuit("umea", "Rally Sweden", "Sweden", "SE", "Europe/Stockholm", "Umea"),
  circuit("naivasha", "Safari Rally Kenya", "Kenya", "KE", "Africa/Nairobi", "Naivasha"),
  circuit("zagreb", "Croatia Rally", "Croatia", "HR", "Europe/Zagreb", "Zagreb"),
  circuit("canary-islands", "Rally Islas Canarias", "Spain", "ES", "Atlantic/Canary", "Las Palmas"),
  circuit("matosinhos", "Rally de Portugal", "Portugal", "PT", "Europe/Lisbon", "Matosinhos"),
  circuit("aichi", "Rally Japan", "Japan", "JP", "Asia/Tokyo", "Aichi"),
  circuit("lamia", "Acropolis Rally Greece", "Greece", "GR", "Europe/Athens", "Lamia"),
  circuit("tartu", "Rally Estonia", "Estonia", "EE", "Europe/Tallinn", "Tartu"),
  circuit("jyvaskyla", "Rally Finland", "Finland", "FI", "Europe/Helsinki", "Jyvaskyla"),
  circuit("encarnacion", "Rally del Paraguay", "Paraguay", "PY", "America/Asuncion", "Encarnacion"),
  circuit("concepcion", "Rally Chile Bio Bio", "Chile", "CL", "America/Santiago", "Concepcion"),
  circuit("sardinia", "Rally Italia Sardegna", "Italy", "IT", "Europe/Rome", "Sardinia"),
  circuit("jeddah-rally", "Rally Saudi Arabia", "Saudi Arabia", "SA", "Asia/Riyadh", "Jeddah"),
  circuit("bikernieki", "Bikernieki Circuit", "Latvia", "LV", "Europe/Riga", "Riga"),
  circuit("nyirad", "Nyirad Racing Center", "Hungary", "HU", "Europe/Budapest", "Nyirad"),
  circuit("holjes", "Holjes Motorstadion", "Sweden", "SE", "Europe/Stockholm", "Holjes"),
  circuit("mondello", "Mondello Park", "Ireland", "IE", "Europe/Dublin", "Naas"),
  circuit("loheac", "Circuit de Loheac", "France", "FR", "Europe/Paris", "Loheac"),
  circuit("lousada", "Eurocircuito de Lousada", "Portugal", "PT", "Europe/Lisbon", "Lousada"),
  circuit("jakarta", "Jakarta Rallycross Circuit", "Indonesia", "ID", "Asia/Jakarta", "Jakarta"),
  circuit("bowman-gray", "Bowman Gray Stadium", "United States", "US", "America/New_York", "Winston-Salem"),
  circuit("atlanta", "EchoPark Speedway", "United States", "US", "America/New_York", "Hampton"),
  circuit("las-vegas-motor", "Las Vegas Motor Speedway", "United States", "US", "America/Los_Angeles", "Las Vegas"),
  circuit("darlington", "Darlington Raceway", "United States", "US", "America/New_York", "Darlington"),
  circuit("martinsville", "Martinsville Speedway", "United States", "US", "America/New_York", "Ridgeway"),
  circuit("bristol", "Bristol Motor Speedway", "United States", "US", "America/New_York", "Bristol"),
  circuit("kansas", "Kansas Speedway", "United States", "US", "America/Chicago", "Kansas City"),
  circuit("talladega", "Talladega Superspeedway", "United States", "US", "America/Chicago", "Lincoln"),
  circuit("texas", "Texas Motor Speedway", "United States", "US", "America/Chicago", "Fort Worth"),
  circuit("dover", "Dover Motor Speedway", "United States", "US", "America/New_York", "Dover"),
  circuit("charlotte", "Charlotte Motor Speedway", "United States", "US", "America/New_York", "Concord"),
  circuit("michigan", "Michigan International Speedway", "United States", "US", "America/Detroit", "Brooklyn"),
  circuit("pocono", "Pocono Raceway", "United States", "US", "America/New_York", "Long Pond"),
  circuit("san-diego", "Naval Base Coronado Street Circuit", "United States", "US", "America/Los_Angeles", "San Diego"),
  circuit("chicagoland", "Chicagoland Speedway", "United States", "US", "America/Chicago", "Joliet"),
  circuit("north-wilkesboro", "North Wilkesboro Speedway", "United States", "US", "America/New_York", "North Wilkesboro"),
  circuit("iowa", "Iowa Speedway", "United States", "US", "America/Chicago", "Newton"),
  circuit("richmond", "Richmond Raceway", "United States", "US", "America/New_York", "Richmond"),
  circuit("new-hampshire", "New Hampshire Motor Speedway", "United States", "US", "America/New_York", "Loudon"),
  circuit("homestead", "Homestead-Miami Speedway", "United States", "US", "America/New_York", "Homestead"),
  circuit("rockingham", "Rockingham Speedway", "United States", "US", "America/New_York", "Rockingham"),
  circuit("lime-rock", "Lime Rock Park", "United States", "US", "America/New_York", "Lakeville"),
  circuit("irp", "Lucas Oil Indianapolis Raceway Park", "United States", "US", "America/Indiana/Indianapolis", "Brownsburg"),
  circuit("saudi-arabia", "Dakar Rally Route", "Saudi Arabia", "SA", "Asia/Riyadh"),
];

const championshipMap = new Map(championships.map((item) => [item.id, item]));
const circuitMap = new Map(circuits.map((item) => [item.id, item]));

export function getChampionship(id: string) {
  const item = championshipMap.get(id);
  if (!item) throw new Error(`Unknown championship: ${id}`);
  return item;
}

export function getCircuit(id: string) {
  const item = circuitMap.get(id);
  if (!item) throw new Error(`Unknown circuit: ${id}`);
  return item;
}
